apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- name: mpod-v1.kb.io
  namespaceSelector:
    matchExpressions:
    - key: accesserator-webhooks
      operator: In
      values:
      - enabled
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - name: vpod-v1.kb.io
    namespaceSelector:
      matchExpressions:
        - key: accesserator-webhooks
          operator: In
          values:
            - enabled
