# This rule is not used by the project accesserator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to accesserator.kartverket.no resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: accesserator
    app.kubernetes.io/managed-by: kustomize
  name: securityconfig-viewer-role
rules:
- apiGroups:
  - accesserator.kartverket.no
  resources:
  - securityconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - accesserator.kartverket.no
  resources:
  - securityconfigs/status
  verbs:
  - get
