# This rule is not used by the project accesserator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the accesserator.kartverket.no.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: accesserator
    app.kubernetes.io/managed-by: kustomize
  name: securityconfig-editor-role
rules:
- apiGroups:
  - accesserator.kartverket.no
  resources:
  - securityconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - accesserator.kartverket.no
  resources:
  - securityconfigs/status
  verbs:
  - get
